version: '3.3'
networks:
  pastecord-network:
    name: pastecord-network
    ipam:
      driver: default
services:
  pastecord:
    container_name: pastecord
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    image: 'yureien/yabin:latest'
    env_file: .env
    depends_on:
      - db
    networks:
      - pastecord-network
  db:
    container_name: pastecord-db
    restart: always
    image: postgres:15-alpine
    env_file: .env
    expose:
      - '5432'
    environment:
      POSTGRES_USER: ${DB_USER:-pastecord_user}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-123}
      POSTGRES_DB: ${DB_NAME:-pastecord_db}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - pastecord-network